hub:
  image: dalmatialab/jupyterhub
  imageTag: 1.0-rc-1
  nodeSelector: false
  secret: 
  storage:
    enabled: true
    volumeMounts:
      - mountPath: /etc/jupyterhub/config/
        name: config
    volumes:
      - name: config
        configMap:
          name: hub-config

proxy:
  nodePort: 
  nodeSelector: false
  secret: 
  
prepull:
  nodeSelector: false
  
singleuserconfig:
  auth:
    admin:
      access: true
      users:
      - admin
    type: dummy
    dummy:
      password: admin
    whitelist:
      users:
      - admin
  singleuser:
    cmd: jupyterhub-singleuser
    defaultUrl: /lab
    events: true
    extraEnv:
    fsGid: 0
    uid: 0
    image:
      name: dalmatialab/jupyterlab
      pullPolicy: Always
      tag: 1.0-rc-1
    imagePullPolicy: Always
    networkTools:
      image:
        name: jupyterhub/k8s-network-tools
        tag: 0.8.2
    nodeSelector:
      jupytersingleuser: "true"
    startTimeout: 800
    storage: